require: rubocop-rspec
AllCops:
  RunRailsCops: true
  Exclude:
    - 'admin/node_modules/**/*'
    - 'db/**/*'
    - 'config/unicorn.rb'
    - 'lib/**/*'
    - 'config/**/*'
    - 'admin/bower_components/**/*'
