before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - bin/setup
branches:
  only:
    - master
cache:
  - bundler
language:
  - ruby
notifications:
  email: false
rvm:
  - 2.2.2
addons:
  postgresql: "9.4"
  code_climate:
     repo_token: 4ee62da4f08d3535bef2f37c58c892d64366defebfa1cd239a74292f8cb08e4d
sudo: false
