before_install:
- echo '--colour' > ~/.rspec
- 'echo ''gem: --no-document'' > ~/.gemrc'
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
install:
- bin/setup
branches:
  only:
  - master
cache:
- bundler
language:
- ruby
notifications:
  email: false
  hipchat:
    rooms:
      secure: n5YJ0ZwNw9yGGkT//PeI/+edvBBYmluzYi1lTXWLog8h5xi2BIfn4ceMdf57OtGVm3TypKvI/dAAgmQizPknaxUy10itRsTkumrTUHEnJoKMpuCPwphiZoJnPGDo0dWi9IgZXRmminTPfk33znfkK58kKw2blb6xbkDN+YyPxB0=
rvm:
- 2.2.2
addons:
  postgresql: '9.4'

sudo: false
